version: "3"
services:
  openjdk:
    image: "maelstrom:1"
    command: ["./maelstrom/maelstrom",  "test", "-w", "echo", "--bin", "/cmd/maelstrom-echo", "--node-count", "1", "--time-limit", "10"]
    volumes:
      - "./cmd:/cmd:z" 
