version: "3"
services:
  openjdk:
    image: "maelstrom:latest"
    command: ["./maelstrom/maelstrom",  "test", "-w", "echo", "--bin", "/cmd/maelstrom-echo", "--node-count", "1", "--time-limit", "10"]
      #    command: ["./maelstrom/maelstrom", "test", "-w", "unique-ids", "--bin", "/cmd/maelstrom-echo", "--node-count", "3", "--time-limit", "30", "--availability", "total", "--nemesis", "partition"]
    volumes:
      - "./cmd:/cmd:z" 
